spring:
  main:
    banner-mode: off

logging:
  level:
    root: INFO

benchmark:
  deltaEnabled: true

productIds:
  BTC-GBP,
  ETH-USDC,
  OMG-EUR,
  FIL-USD,
  XTZ-USD,
  BAND-GBP,
  CGLD-GBP,
  MKR-BTC,

  BAL-USD,
  LTC-USD,
  DNT-USDC,
  FIL-EUR,
  MANA-USDC,
  FIL-BTC,
  XLM-USD,
  LOOM-USDC,

  NMR-USD,
  CVC-USDC,
  UMA-GBP,
  UNI-USD,
  ETH-EUR,
  BAT-USDC,
  OMG-EUR,
  ATOM-USD,

  NU-USD,
  ETH-USDC,
  NMR-GBP,
  KNC-USD,
  ZEC-BTC,
  AAVE-EUR,
  ALGO-BTC,
  XTZ-USD,

  NU-EUR,
  XLM-BTC,
  LTC-GBP,
  LRC-BTC,
  ALGO-EUR,
  GRT-USD,
  MKR-USD,
  ETC-USD,

  DASH-USD,
  BTC-USDC,
  REP-BTC,
  ETH-GBP,
  BAND-BTC,
  BNT-BTC,
  BAL-BTC,
  UMA-EUR,

  ETH-DAI,
  ETC-GBP,
  EOS-EUR,
  BAT-ETH,
  AAVE-GBP,
  SNX-GBP,
  CGLD-EUR,
  YFI-USD,

  XLM-EUR,
  OMG-USD,
  EOS-BTC,
  BCH-BTC,
  LINK-GBP,
  COMP-BTC,
  ZRX-EUR,
  BTC-EUR,

  GRT-GBP,
  ZRX-USD,
  FIL-GBP,
  CGLD-GBP,
  LRC-USD,
  BCH-EUR,
  AAVE-BTC,
  FIL-USD

option: C

productA:
  BTC-GBP,
  ETH-USDC,
  OMG-EUR,
  FIL-USD,
  XTZ-USD,
  BAND-GBP,
  CGLD-GBP,
  MKR-BTC,

  BAL-USD,
  LTC-USD,
  DNT-USDC,
  FIL-EUR,
  MANA-USDC,
  FIL-BTC,
  XLM-USD,
  LOOM-USDC,

  NMR-USD,
  CVC-USDC,
  UMA-GBP,
  UNI-USD,
  ETH-EUR,
  BAT-USDC,
  OMG-EUR,
  ATOM-USD,

  NU-USD,
  ETH-USDC,
  NMR-GBP,
  KNC-USD,
  ZEC-BTC,
  AAVE-EUR,
  ALGO-BTC,
  XTZ-USD,

  NU-EUR,
  XLM-BTC,
  LTC-GBP,
  LRC-BTC,
  ALGO-EUR,
  GRT-USD,
  MKR-USD,
  ETC-USD

productB:
  DASH-USD,
  BTC-USDC,
  REP-BTC,
  ETH-GBP,
  BAND-BTC,
  BNT-BTC,
  BAL-BTC,
  UMA-EUR,

  ETH-DAI,
  ETC-GBP,
  EOS-EUR,
  BAT-ETH,
  AAVE-GBP,
  SNX-GBP,
  CGLD-EUR,
  YFI-USD,

  XLM-EUR,
  OMG-USD,
  EOS-BTC,
  BCH-BTC,
  LINK-GBP,
  COMP-BTC,
  ZRX-EUR,
  BTC-EUR,

  GRT-GBP,
  ZRX-USD,
  FIL-GBP,
  CGLD-GBP,
  LRC-USD,
  BCH-EUR,
  AAVE-BTC,
  FIL-USD