spring:
  profiles:
    include: common

server:
  port: 8080

orderPort: 5555
exceptionPort: 5557

websocket:
  baseUrl: "wss://ws-feed.pro.coinbase.com"
  enabled: true

security:
  enabled: true
  privateKey: "8E0BDD697628B91D8F245587EE95C5B04D48963F79259877B49CD9063AEAD3B7"